apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    {{- include "sample.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "sample.selectorLabels" . | nindent 4 }}
    app: {{ .Values.nginx.label }}
  ports:
  - port: {{ .Values.nginx.service.port }}
    targetPort: {{ .Values.nginx.service.port }}
